# Generated by Django 5.0.1 on 2024-01-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogposts',
            new_name='Itemblogposts',
        ),
    ]
