# Generated by Django 5.0.1 on 2024-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogposts_itemblogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemblogposts',
            name='idNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
